import pg from 'pg';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {randomBytes} from 'node:crypto';
import assert from 'node:assert/strict';
import {createApplication} from '../backend/server.js';
import {configuration} from '../backend/config.mjs';
const cfg=JSON.parse(await readFile('.runtime/test.json','utf8'));
const owner=new pg.Client({host:'127.0.0.1',port:55432,user:'postgres',database:cfg.database});await owner.connect();
const directory=(await owner.query('SHOW data_directory')).rows[0].data_directory.replaceAll('\\','/').toLowerCase();assert(directory.endsWith('/nexuscup/.test_pgdata'));
const {server,pool}=createApplication({db:{host:'127.0.0.1',port:55432,user:cfg.user,password:cfg.password,database:cfg.database},key:cfg.key});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
const results=[];let failures=0;
async function test(name,fn){try{await fn();results.push({name,result:'PASS'});console.log('PASS',name);}catch(e){failures++;results.push({name,result:'FAIL',error:e.stack});console.error('FAIL',name,e.message);}}
async function request(path,{cookie='',body,status=200}={}){const r=await fetch(base+'/api/'+path,{method:body?'POST':'GET',headers:{...(cookie?{Cookie:cookie}:{}),...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const d=await r.json();assert.equal(r.status,status,JSON.stringify(d));return {data:d,cookie:r.headers.get('set-cookie')?.split(';')[0]};}
const cmd=(cookie,acao,dados={},status=200)=>request('command',{cookie,body:{acao,dados},status}).then(x=>x.data);
const q=(sql,p=[])=>owner.query(sql,p).then(r=>r.rows);
async function dbTest(name,sql,failCode){await test(name,async()=>{await q('BEGIN');await q("select set_config('nexus.key',$1,true),set_config('nexus.actor','1',true)",[cfg.key]);try{if(failCode){await assert.rejects(()=>q(sql),e=>e.code===failCode);}else await q(sql);}finally{await q('ROLLBACK');}});}
try{
 await test('Configuração rejeita portas PostgreSQL fora da allowlist sem conexão',()=>{assert.throws(()=>configuration({PGPORT:'12345'}),/apenas/);});
 await test('Cluster pertence à working tree canónica',async()=>assert(directory.endsWith('/nexuscup/.test_pgdata')));
 await test('Dataset inicial: 12 históricos homologados; 1 agendado e 11 não agendados',async()=>{
 assert.deepEqual(await q('select epoca_id,estado,count(*)::int n from competicao.jogo group by epoca_id,estado order by epoca_id,estado'),[{epoca_id:1,estado:'HOMOLOGADO',n:12},{epoca_id:2,estado:'AGENDADO',n:1},{epoca_id:2,estado:'NAO_AGENDADO',n:11}]);
 assert.equal((await q('select count(*)::int n from seguranca.operacao'))[0].n,24);
 const types=await q('select distinct tipo from jogo.evento');for(const t of ['GOLO','FALTA','SUBSTITUICAO','AMARELO','EXPULSAO_SEGUNDO_AMARELO'])assert(types.some(x=>x.tipo===t));
 assert.equal((await q('select count(*)::int n from seguranca.ocorrencia where uso_forca'))[0].n,1);
 });
 await dbTest('DB: equipa contra si rejeitada',"INSERT INTO competicao.jogo(epoca_id,jornada_id,casa_id,fora_id,recinto_esperado) VALUES(2,7,1,1,1)",'23514');
 await dbTest('DB: FK inválida rejeitada',"INSERT INTO clubes.equipa(clube_id,nome,recinto_id) VALUES(99999,'Equipa inexistente',1)",'23503');
 await dbTest('DB: camisola inválida rejeitada',"UPDATE clubes.camisola SET fim='2026-12-31' WHERE vinculo_id=1; INSERT INTO clubes.camisola(vinculo_id,equipa_id,numero,inicio,fim) VALUES(1,1,0,'2027-01-01','2027-03-01')",'23514');
 await dbTest('DB: sobreposição temporal rejeitada pelo trigger',"INSERT INTO clubes.camisola(vinculo_id,equipa_id,numero,inicio,fim) VALUES(2,1,1,'2026-09-20','2026-12-31')",'P0001');
 await dbTest('DB: reutilização sem sobreposição aceite',"UPDATE clubes.camisola SET fim='2026-12-31' WHERE vinculo_id IN(1,2); INSERT INTO clubes.camisola(vinculo_id,equipa_id,numero,inicio,fim) VALUES(2,1,1,'2027-01-01','2027-06-30')");
 await dbTest('DB: pairing casa/fora duplicado rejeitado',"INSERT INTO competicao.jogo(epoca_id,jornada_id,casa_id,fora_id,recinto_esperado) VALUES(2,8,1,4,1)",'23505');
 await dbTest('DB: jogador de outra equipa não elegível',"INSERT INTO jogo.convocado(jogo_id,vinculo_id,camisola_id,equipa_id,pessoa_id,numero,titular,estado) VALUES(13,9,8,2,9,1,true,'EM_CAMPO')",'P0001');
 await dbTest('DB: resultado oficial imutável',"UPDATE competicao.resultado SET casa=99 WHERE jogo_id=1",'P0001');
 await dbTest('DB: delete histórico rejeitado',"DELETE FROM jogo.evento WHERE jogo_id=1",'P0001');
 await dbTest('DB: finalização direta antecipada rejeitada',"UPDATE competicao.jogo SET estado='FINALIZADO' WHERE id=13",'P0001');
 await dbTest('DB: força sem justificação rejeitada',"INSERT INTO seguranca.ocorrencia(operacao_id,descricao,envolvidos,evidencia,sha256,uso_forca) VALUES(13,'Teste ocorrência','Intervenientes','Auto de teste',repeat('a',64),true)",'23514');
 await test('Role runtime sem privilégios DML nem acesso direto a evidência',async()=>{for(const sql of ['SELECT * FROM forense.registo','SELECT * FROM app.utilizador',"SELECT app.command(1,'SUPER','{}')","UPDATE competicao.jogo SET estado='HOMOLOGADO' WHERE id=13"]){await assert.rejects(()=>pool.query(sql),e=>e.code==='42501');}});
 await test('Saúde API + frontend estático',async()=>{const h=(await request('health')).data;assert.equal(h.product,'NEXUS-CUP');assert.equal(h.db_port,55432);const html=await fetch(base).then(r=>r.text());assert(html.includes('NEXUS-CUP V1.0'));assert(!html.includes('SUPER_AUDITOR'));});
 const initial=process.env.NEXUS_BOOTSTRAP_PASSWORD;if(!initial)throw Error('Definir NEXUS_BOOTSTRAP_PASSWORD apenas no ambiente dos testes');
 let adminCookie,readerCookie,normalAdminCookie;
 await test('Login e mudança obrigatória da password inicial',async()=>{const login=await request('login',{body:{email:'Alfcybercop@nexuscup.pt',password:initial}});adminCookie=login.cookie;assert(login.data.mudar_password);await request('catalogo',{cookie:adminCookie,status:428});await cmd(adminCookie,'PASSWORD',{nova:'Teste!'+randomBytes(16).toString('hex')});assert.equal((await request('me',{cookie:adminCookie})).data.mudar_password,false);});
 const catalog=(await request('catalogo',{cookie:adminCookie})).data;
 const jid=14;let state;
 const load=async()=>state=(await request('jogo?jogo_id='+jid,{cookie:adminCookie})).data;
 const c=(a,b={},status=200)=>cmd(adminCookie,a,{jogo_id:jid,...b},status);
 await test('E2E: NÃO AGENDADO → AGENDAR → recinto auditado sem RED',async()=>{await load();assert.equal(state.jogo.estado,'NAO_AGENDADO');const red=(await q('select count(*)::int n from auditoria.intencao'))[0].n;await c('AGENDAR',{inicio:'2026-10-04T15:00:00Z'});await c('RECINTO',{recinto_id:1,motivo:'Recinto habitual em manutenção programada'});await load();assert.equal(state.jogo.estado,'AGENDADO');assert.equal(state.jogo.recinto_id,1);assert.equal((await q('select count(*)::int n from auditoria.intencao'))[0].n,red);});
 await test('E2E: arbitragem e segurança independentes',async()=>{for(const [funcao,pessoa_id] of [['ARBITRO',33],['SEGUNDO_ARBITRO',34],['CRONOMETRISTA',35]])await c('ARBITRAGEM',{funcao,pessoa_id});await c('PREPARAR_SEGURANCA',{responsavel_id:37,agentes:[39,40]});await c('INICIAR_SEGURANCA');await load();assert.equal(state.seguranca.estado,'EM_CURSO');});
 await test('E2E: convocatória real e INICIAR',async()=>{await load();for(const p of state.elegiveis)await c('CONVOCAR',{vinculo_id:p.vinculo_id,camisola_id:p.camisola_id,titular:p.numero<=5,goleiro:p.numero===1});await c('EVENTO',{tipo:'INICIO',periodo:1,segundos:0});await load();assert.equal(state.jogo.estado,'EM_CURSO');assert.equal(state.convocados.filter(x=>x.estado==='EM_CAMPO').length,10);});
 await load();let home=state.convocados.filter(x=>x.equipa_id===state.jogo.casa_id),away=state.convocados.filter(x=>x.equipa_id===state.jogo.fora_id);const h=n=>home.find(x=>x.numero===n),f=n=>away.find(x=>x.numero===n);
 const ev=(tipo,periodo,segundos,jogador,entra,detalhe={})=>c('EVENTO',{tipo,periodo,segundos,equipa_id:jogador?.equipa_id||entra?.equipa_id,jogador_id:jogador?.id,entra_id:entra?.id,detalhe});
 await test('E2E: GOLO → SUBSTITUIÇÃO → FALTA → AMARELO',async()=>{await ev('GOLO',1,235,h(2));await ev('SUBSTITUICAO',1,600,h(3),h(6));await ev('FALTA',1,650,f(2),null,{classe:'DIRETO'});await ev('AMARELO',1,650,f(2));await load();assert.equal(state.jogo.golos_casa,1);assert.equal(state.convocados.find(x=>x.id===h(3).id).estado,'BANCO');});
 await test('E2E: INTERVALO → segunda parte sem segundo artificial',async()=>{await ev('INTERVALO',1,1200);await ev('SEGUNDA_PARTE',2,0);await load();assert.equal(state.jogo.segundos,0);assert.equal(state.eventos.at(-1).tempo,'20:01');});
 await test('E2E: segundo amarelo, expulsão e redução da EQUIPA',async()=>{await ev('AMARELO',2,135,f(2));await load();assert.equal(state.convocados.find(x=>x.id===f(2).id).estado,'EXPULSO');assert.equal(state.reducoes.length,1);assert.equal(state.eventos.at(-1).tipo,'EXPULSAO_SEGUNDO_AMARELO');assert.equal(state.eventos.at(-1).segundos,135);});
 await test('DB/API: expulso não regressa',async()=>{await c('EVENTO',{tipo:'SUBSTITUICAO',periodo:2,segundos:135,equipa_id:f(3).equipa_id,jogador_id:f(3).id,entra_id:f(2).id},409);});
 await test('DB/API: reposição prematura rejeitada',async()=>{await c('EVENTO',{tipo:'REPOSICAO',periodo:2,segundos:135,equipa_id:f(6).equipa_id,entra_id:f(6).id,detalhe:{autorizado_por:'CRONOMETRISTA'}},409);});
 await test('E2E: golo em superioridade liberta uma reposição autorizada',async()=>{await ev('GOLO',2,135,h(2));await ev('REPOSICAO',2,135,null,f(6),{autorizado_por:'CRONOMETRISTA'});await load();assert(state.reducoes[0].causa.startsWith('GOLO:'));assert(state.reducoes[0].entrada_evento);assert.equal(state.convocados.find(x=>x.id===f(2).id).estado,'EXPULSO');});
 await test('DB/API: concorrência e múltiplos eventos no mesmo segundo',async()=>{await Promise.all([ev('FALTA',2,135,h(4),null,{classe:'DIRETO'}),ev('FALTA',2,135,f(4),null,{classe:'DIRETO'})]);await load();assert(state.eventos.filter(x=>x.periodo===2&&x.segundos===135).length>=6);assert.deepEqual(state.eventos.map(x=>x.seq),state.eventos.map((_,i)=>i+1));});
 await test('E2E: INTERRUPÇÃO 31:47 → RETOMA 31:47',async()=>{await ev('INTERRUPCAO',2,707);await load();assert.equal(state.jogo.estado,'INTERROMPIDO');await ev('RETOMA',2,707);await load();assert.equal(state.jogo.segundos,707);assert.equal(state.jogo.estado,'EM_CURSO');});
 await test('DB/API: finalização prematura recusada',async()=>{await c('EVENTO',{tipo:'FIM',periodo:2,segundos:1100},409);});
 await test('E2E: finalização aos 40:00 preserva segurança aberta',async()=>{await ev('SUBSTITUICAO',2,800,h(6),h(3));await ev('FIM',2,1200);await load();assert.equal(state.jogo.estado,'FINALIZADO');assert.equal(state.jogo.segundos,1200);assert.equal(state.seguranca.estado,'EM_CURSO');assert(!state.convocados.some(x=>x.estado==='FINALIZADO'));});
 await test('E2E: ocorrência pós-jogo → homologação bloqueada',async()=>{await c('OCORRENCIA',{descricao:'Acompanhamento de espectador na saída após final da partida',envolvidos:'Espectador fictício e equipa de apoio',evidencia:'Auto de acompanhamento pós-jogo',feridos:0,uso_forca:false});const r=await c('HOMOLOGAR',{},409);assert.match(r.erro,/segurança/i);});
 await test('E2E: FINALIZAR SEGURANÇA → HOMOLOGAR explicitamente',async()=>{await c('FINALIZAR_SEGURANCA',{avaliacao:'Público saiu em segurança. Auto conferido.'});await load();assert(state.readiness.pronto);await c('HOMOLOGAR');await load();assert.equal(state.jogo.estado,'HOMOLOGADO');assert.equal(state.resultados.length,1);});
 let intent;
 await test('E2E: intenção pós-fecho imediatamente persistida',async()=>{intent=await cmd(adminCookie,'INTENCAO',{objeto:'JOGO',objeto_id:jid,motivo:'Revisão documental do golo atribuído'});assert.equal((await q('select count(*)::int n from auditoria.intencao where id=$1',[intent.id]))[0].n,1);});
 await test('E2E: retificação executada preserva evento, sequência e versão original',async()=>{const goal=state.eventos.find(e=>e.tipo==='GOLO');const before=state.eventos.map(e=>e.seq);await cmd(adminCookie,'RETIFICAR',{intencao_id:intent.id,tipo:'GOLO',evento_id:goal.id,valido:false});await load();assert.equal(state.resultados.length,2);assert.equal(state.resultados[0].casa,2);assert.equal(state.resultados[1].casa,1);assert.deepEqual(state.eventos.map(e=>e.seq),before);assert.equal(state.jogo.golos_casa,1);});
 await test('E2E: tentativa rejeitada pela DB permanece auditada',async()=>{const i=await cmd(adminCookie,'INTENCAO',{objeto:'JOGO',objeto_id:jid,motivo:'Verificação de referência documental incorreta'});const r=await cmd(adminCookie,'RETIFICAR',{intencao_id:i.id,tipo:'GOLO',evento_id:999999,valido:false},409);assert.equal(r.resultado,'REJEITADA');assert.equal((await q('select resultado from auditoria.desfecho where intencao_id=$1',[i.id]))[0].resultado,'REJEITADA');});
 await test('E2E: cancelamento de retificação preservado',async()=>{const i=await cmd(adminCookie,'INTENCAO',{objeto:'SEGURANCA',objeto_id:state.seguranca.id,motivo:'Conferência do auto sem alteração necessária'});await cmd(adminCookie,'CANCELAR_RETIFICACAO',{intencao_id:i.id});assert.equal((await q('select resultado from auditoria.desfecho where intencao_id=$1',[i.id]))[0].resultado,'CANCELADA');});
 await test('E2E: Super Auditor consulta evidência real e leitura meta-auditada',async()=>{const s=(await request('super',{cookie:adminCookie})).data;assert(s.red_flags.some(x=>x.id===intent.id));const detail=(await request('super/detalhe?id='+intent.id,{cookie:adminCookie})).data;assert(detail.forense.length>0);assert(detail.auditoria.length>0);assert(detail.meta.length>0);assert(detail.integridade.integra);});
 await test('RBAC: criação de leitores e administradores sem Super Auditoria',async()=>{for(const role of ['LEITOR','ADMIN']){const password='Initial!'+randomBytes(12).toString('hex');const email=role.toLowerCase()+'@tests.invalid';await cmd(adminCookie,'CRIAR_UTILIZADOR',{nome:role==='ADMIN'?'Rita Valenço':'Tomás Silveiral',email,password,role});const r=await request('login',{body:{email,password}});await cmd(r.cookie,'PASSWORD',{nova:'Nova!'+randomBytes(16).toString('hex')});if(role==='LEITOR')readerCookie=r.cookie;else normalAdminCookie=r.cookie;}});
 await test('E2E: Super Auditoria negada e auditada para leitor, admin normal e anónimo',async()=>{for(const cookie of [readerCookie,normalAdminCookie,''])await request('super',{cookie,status:403});const rows=await q('select count(*)::int n from auditoria.meta where not permitido');assert(rows[0].n>=3);await cmd(readerCookie,'SUPER_DETALHE',{id:intent.id},403);});
 await test('RBAC: leitor não altera dados e admin não concede Super Auditor',async()=>{await cmd(readerCookie,'RECINTO',{jogo_id:13,recinto_id:2,motivo:'Pedido sem permissão'},403);await cmd(normalAdminCookie,'CRIAR_UTILIZADOR',{nome:'Sem Acesso',email:'denied@tests.invalid',password:'LongPassword!234',role:'SUPER_AUDITOR'},403);});
 await test('Relatórios reais, resultados coerentes e zero evidência RED em endpoints normais',async()=>{for(const tipo of ['resultados','jogadores','golos','cartoes','classificacao','faltas','seguranca'])assert(Array.isArray((await request('relatorio?epoca_id=1&tipo='+tipo,{cookie:readerCookie})).data));const normal=(await request('jogo?jogo_id='+jid,{cookie:readerCookie})).data;assert(!JSON.stringify(normal).includes('cipher'));assert(!('red_flags' in normal));const mismatch=await q(`select j.id from competicao.v_jogos_resultados j join lateral (select * from competicao.resultado r where r.jogo_id=j.id order by versao desc limit 1) r on true where r.casa<>j.golos_casa or r.fora<>j.golos_fora`);assert.equal(mismatch.length,0);});
 await test('Integridade forense verificável após E2E e rejeições',async()=>{const r=(await request('super/integridade',{cookie:adminCookie})).data;assert.equal(r.integra,true);assert.equal(r.registos,(await q('select count(*)::int n from forense.registo'))[0].n);assert(r.registos>0);});
 await test('Integridade deteta adulteração controlada, revertida por ROLLBACK',async()=>{await q('BEGIN');try{await q('ALTER TABLE forense.registo DISABLE TRIGGER imutavel');await q("UPDATE forense.registo SET categoria='ALTERADA' WHERE id=(SELECT min(id) FROM forense.registo)");assert.equal((await q('select forense.verificar() result'))[0].result.integra,false);}finally{await q('ROLLBACK');}});
 await test('Concurrent jersey assignment rejects overlap',async()=>{
 await q('BEGIN');await q("select set_config('nexus.key',$1,true),set_config('nexus.actor','1',true)",[cfg.key]);
 const vs=[];for(const nome of ['Gil Figueiral de Teste','Rui Soutelo de Teste']){const p=(await q('insert into nucleo.pessoa(nome) values($1) returning id',[nome]))[0].id;vs.push((await q("insert into clubes.vinculo(equipa_id,pessoa_id,funcao,inicio,fim) values(1,$1,'JOGADOR','2028-01-01','2028-12-31') returning id",[p]))[0].id);}await q('COMMIT');
 const a=new pg.Client({host:'127.0.0.1',port:55432,user:'postgres',database:cfg.database}),b=new pg.Client({host:'127.0.0.1',port:55432,user:'postgres',database:cfg.database});await a.connect();await b.connect();
 try{for(const client of [a,b]){await client.query('BEGIN');await client.query("select set_config('nexus.key',$1,true),set_config('nexus.actor','1',true),set_config('statement_timeout','5000',true)",[cfg.key]);}
 await a.query("insert into clubes.camisola(vinculo_id,equipa_id,numero,inicio,fim) values($1,1,90,'2028-01-01','2028-12-31')",[vs[0]]);
 const pending=b.query("insert into clubes.camisola(vinculo_id,equipa_id,numero,inicio,fim) values($1,1,90,'2028-01-01','2028-12-31')",[vs[1]]);const check=assert.rejects(pending,/sobreposto/);await a.query('COMMIT');await check;
 }finally{await a.query('ROLLBACK');await b.query('ROLLBACK');await a.end();await b.end();}
 });
}catch(e){failures++;results.push({name:'EXECUÇÃO',result:'FAIL',error:e.stack});console.error(e);}finally{
 await mkdir('test-results',{recursive:true});await writeFile('test-results/results.json',JSON.stringify({database:cfg.database,at:new Date().toISOString(),passed:results.filter(x=>x.result==='PASS').length,failed:failures,results},null,2));
 await owner.end();await new Promise(r=>server.close(r));
 console.log(JSON.stringify({passed:results.filter(x=>x.result==='PASS').length,failed:failures}));process.exitCode=failures?1:0;
}
