import {spawn} from 'node:child_process';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {randomBytes} from 'node:crypto';
import assert from 'node:assert/strict';
import {chromium} from 'playwright-core';
import {createApplication} from '../backend/server.js';
import pg from 'pg';
const results=[],errors=[];let server,browser,page;
async function test(name,fn){await fn();results.push({name,result:'PASS'});console.log('PASS',name);}
async function install(){const owner=new pg.Client({host:'127.0.0.1',port:55432,user:'postgres',database:'postgres'});await owner.connect();assert((await owner.query('show data_directory')).rows[0].data_directory.replaceAll('\\','/').toLowerCase().endsWith('/nexuscup/.test_pgdata'));await owner.end();
 return new Promise((resolve,reject)=>{const p=spawn(process.execPath,['installer/install.mjs'],{stdio:['pipe','pipe','pipe'],windowsHide:true});let out='',err='';p.stdout.on('data',x=>out+=x);p.stderr.on('data',x=>err+=x);p.on('error',reject);p.on('exit',code=>code?reject(Error(err)):resolve(JSON.parse(out)));p.stdin.end(JSON.stringify({port:55432,test:true,user:'postgres',database:'nexuscup_install_'+Date.now()}));});}
try{
 let cfg;await test('Instalador real: BD nova, baseline, datasets, autenticação, HTTP e frontend',async()=>{cfg=await install();assert(cfg.validated);await mkdir('.runtime',{recursive:true});await writeFile('.runtime/ui.json',JSON.stringify(cfg));});
 ({server}=createApplication({db:{host:'127.0.0.1',port:55432,user:cfg.user,password:cfg.password,database:cfg.database},key:cfg.key}));await new Promise(r=>server.listen(0,'127.0.0.1',r));
 browser=await chromium.launch({channel:'msedge',headless:true});const ctx=await browser.newContext({viewport:{width:1440,height:1000}});page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));
 await mkdir('test-results/ui',{recursive:true});
 const button=name=>page.getByRole('button',{name,exact:true});
 const save=async()=>{await button('Guardar').click();await page.locator('#modal').waitFor({state:'hidden'});};
 await test('UI: login e alteração obrigatória da password',async()=>{await page.goto('http://127.0.0.1:'+server.address().port);await page.getByLabel('Email',{exact:true}).fill('Alfcybercop@nexuscup.pt');await page.getByLabel('Password',{exact:true}).fill(process.env.NEXUS_BOOTSTRAP_PASSWORD);await button('Entrar').click();await page.getByRole('heading',{name:'Alterar password'}).waitFor();const pw='UiTeste!'+randomBytes(12).toString('hex');await page.getByLabel('Nova password',{exact:true}).fill(pw);await page.getByLabel('Repetir password').fill(pw);await button('Guardar e entrar').click();await page.locator('#shell').waitFor({state:'visible'});await page.getByRole('heading',{name:'Dashboard operacional'}).waitFor();});
 await test('UI: dashboard claro com contadores e Super Auditoria restrita',async()=>{await page.locator('[data-filter="NAO_AGENDADO"] b').waitFor();assert.equal(await page.locator('[data-filter="NAO_AGENDADO"] b').innerText(),'11');assert.equal(await page.locator('[data-filter="AGENDADO"] b').innerText(),'1');await page.screenshot({path:'test-results/ui/dashboard.png',fullPage:true});});
 await test('UI: contador abre lista e jogo não agendado permite agendar',async()=>{await page.locator('[data-filter="NAO_AGENDADO"]').click();await page.locator('[data-game]').first().click();await button('Agendar').click();await page.getByLabel('Data e hora').fill('2026-12-12T15:00');await save();await button('Iniciar jogo').waitFor();});
 await test('UI: recinto override mostra aviso laranja',async()=>{await button('Alterar recinto').click();await page.getByLabel('Recinto utilizado').selectOption({index:0});await page.getByLabel('Motivo',{exact:true}).fill('Pavilhão habitual em manutenção');await save();await page.getByText('Recinto alterado manualmente',{exact:true}).waitFor();});
 await test('UI: arbitragem com seleção por nome',async()=>{await button('ARBITRAGEM').click();await button('Associar oficial').click();await page.getByLabel('Oficial',{exact:true}).selectOption({label:'Inês Casteleira'});await save();await page.getByRole('cell',{name:'Inês Casteleira'}).waitFor();});
 await test('UI: preparar e iniciar operação de segurança',async()=>{await button('SEGURANÇA').click();await button('Preparar operação').click();await page.getByLabel('Responsável',{exact:true}).selectOption({label:'Carolina Soutelo'});await save();await button('Iniciar operação').click();await page.getByRole('heading',{name:'Operação EM_CURSO'}).waitFor();});
 await test('UI: convocatória distingue titulares, suplentes e guarda-redes',async()=>{await button('PLANTÉIS').click();await button('Selecionar jogadores').click();const panels=page.locator('#dialogForm .panel');for(let n=0;n<await panels.count();n++){const panel=panels.nth(n);await panel.getByLabel('Convocar',{exact:true}).check();const shirt=Number((await panel.locator('b').innerText()).match(/#(\d+)/)[1]);if(shirt<=5)await panel.getByLabel('Titular',{exact:true}).check();if(shirt===1)await panel.getByLabel('Guarda-redes',{exact:true}).check();}await save();assert.equal(await page.getByRole('cell',{name:'EM_CAMPO',exact:true}).count(),10);});
 await test('UI: simulador persistente finaliza a 40:00',async()=>{await button('JOGO').click();await button('Simular jogo completo').click();await page.getByRole('heading',{name:/Estado aos 40:00/}).waitFor();await page.screenshot({path:'test-results/ui/cockpit.png',fullPage:true});});
 await test('UI: tentativa de homologação com segurança aberta bloqueada',async()=>{await button('Homologar').click();await page.locator('#message').filter({hasText:/Homologação bloqueada/}).waitFor();assert.equal(await button('Homologar').count(),1);});
 await test('UI: ocorrência pós-jogo e fecho independente da operação',async()=>{await button('SEGURANÇA').click();await button('Registar ocorrência').click();await page.getByLabel('Descrição',{exact:true}).fill('Acompanhamento preventivo na saída após o jogo');await page.getByLabel('Envolvidos',{exact:true}).fill('Equipa de apoio e espectadores fictícios');await page.getByLabel('Evidência / auto').fill('Auto preventivo de acompanhamento de saída');await save();await button('Finalizar operação').click();await page.getByLabel('Avaliação posterior').fill('Operação concluída. Auto revisto e saída sem incidentes adicionais.');await save();await page.getByRole('heading',{name:'Operação FINALIZADA'}).waitFor();});
 await test('UI: homologação explícita e retificação com versão preservada',async()=>{await button('JOGO').click();await button('Homologar').click();await button('Entrar em retificação').waitFor();await button('Entrar em retificação').click();await page.getByLabel('Motivo',{exact:true}).fill('Conferência do relatório identifica golo indevidamente atribuído');await button('Guardar').click();await page.getByRole('heading',{name:'Retificação em curso'}).waitFor();await save();await page.getByRole('cell',{name:'2',exact:true}).first().waitFor();});
 await test('UI: Super Auditoria e drilldown real',async()=>{await button('Super Auditoria').click();await page.getByRole('heading',{name:'Intervenções sobre objetos fechados'}).waitFor();await page.locator('[data-action="drill"]').first().click();await page.getByRole('heading',{name:'Evidência e correlação'}).waitFor();const txt=await page.locator('#modalBody pre').innerText();assert(txt.includes('EXECUTADA'));assert(txt.includes('forense'));await page.screenshot({path:'test-results/ui/super-auditoria.png',fullPage:true});await button('Fechar').click();});
 await test('UI: relatórios e plantéis sem erros de JavaScript',async()=>{await button('Relatórios').click();await page.locator('#report table').waitFor();await page.getByLabel('Relatório',{exact:true}).selectOption('classificacao');await page.locator('#report table').waitFor();await button('Equipas e plantéis').click();await page.getByRole('heading',{name:'Equipas e plantéis'}).waitFor();assert.equal(errors.length,0,errors.join('\n'));});
}catch(e){console.error(e);results.push({name:'EXECUÇÃO UI',result:'FAIL',error:e.stack});if(page)await page.screenshot({path:'test-results/ui/failure.png',fullPage:true}).catch(()=>{});}finally{if(browser)await browser.close();if(server)await new Promise(r=>server.close(r));await writeFile('test-results/ui.json',JSON.stringify(results,null,2));process.exitCode=results.some(x=>x.result==='FAIL')?1:0;}
